; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters =
	esp32_exception_decoder
	colorize
board_build.flash_mode = dio
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
build_flags =
    -DUSER_SETUP_LOADED=1

    ; Define the driver
    -DST7789_DRIVER=1

    ; Define the pins for ESP32-2432S028 (CYD)
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=21

    ; Fix the Red/Blue color swap
    -DTFT_RGB_ORDER=TFT_BGR

    ; Invert colors if the screen looks like a photo negative
    ; -DTFT_INVERSION_ON

    ; Load Fonts
	-DLOAD_GLCD=1  ; Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
	-DLOAD_FONT2=1 ; Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
	-DLOAD_FONT4=1 ; Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
	-DLOAD_FONT6=1 ; Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
	-DLOAD_FONT7=1 ; Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:-.
	-DLOAD_FONT8=1 ; Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
; 	-DLOAD_FONT8N=1 ; Font 8. Alternative to Font 8 above, slightly narrower, so 3 digits fit a 160 pixel TFT
	-DLOAD_GFXFF=1 ; FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts

; Comment out the #define below to stop the SPIFFS filing system and smooth font code being loaded
; this will save ~20kbytes of FLASH
	-DSMOOTH_FONT=1

    ; SPI Speed (55MHz is usually stable for writing)
    -DSPI_FREQUENCY=55000000
    -DSPI_READ_FREQUENCY=20000000
    -DSPI_TOUCH_FREQUENCY=2500000

	-DCORE_DEBUG_LEVEL=1
	-DUSE_HSPI_PORT=1

	-DTOUCH_CS=33
lib_deps =
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
	bodmer/TFT_eSPI@^2.5.43
board_build.partitions = default.csv
